[package]
name = "mitsuba-raster"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
cgmath = "0.18.0"
num = "0.4.0"
tobj = "3.2.0"
clap = "2.33.3"